### ISSUE TITLE
Unable to download data

### ISSUE THREAD

**Issue by levin422** [SCECcode/CFM_web#1]
I am able to download the fault metadata, but the native+metadata, 500m+metadata, and 1000m+metadata options do not appear to work.

Steps to reproduce:
1. Select one or more faults
2. Click on the 500m+metadata download radio button
3. Nothing happens
Expected Result: Download of data.

The following error appears in the console log:
```
Uncaught ReferenceError: cnt is not defined
    at downloadURLsAsZip (cfm_util.js:121)
    at startDownload (cfm_util.js:212)
    at changeDownloadSet (cfm_util.js:196)
    at HTMLFormElement.onchange (cfm_view.html:1)
```

**Comment by meihuisu** [comment]
added the missing statement
@levin422 please try and let me know

**Comment by levin422** [comment]
Works now! Thank you!
