### ISSUE TITLE
CFM Viewer not working on IE 11

### ISSUE THREAD

**Issue by levin422** [SCECcode/CFM_web#2]
A JavaScript error prevents the CFM Viewer from working on IE11. See below:

<img width="1421" alt="Screen Shot 2019-04-17 at 4 57 03 PM" src="https://user-images.githubusercontent.com/6467986/56328051-0912d900-6132-11e9-97f1-806698161d73.png">

**Comment by levin422** [comment]
Here's what I use to test on Windows/Internet Explorer:
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by levin422** [comment]
9485c892934f99626004d5a0c330d5e30ac43424 doesn't work on IE and breaks in other browsers too. Even after fixing that (71c87d511d9b9c268c914ef4b605dc58d275d3bd), there are other errors in IE 11. 

@pjmaechling, @meihuisu: I suggest we set a list of supported browsers, and not support IE 11. It has less than 3% [browser marketshare worldwide](http://gs.statcounter.com/browser-version-market-share). I suggest we officially support the latest versions of:
- Firefox
- Chrome
- Safari
- Microsoft Edge

I'll add it to the list to discuss with Scott as we move closer to the annual meeting.

**Comment by meihuisu** [comment]
Hi,

 The fix in cfm_layer.js needs to be refixed. That one does not work. I found another solution. I
will commit it shortly.

Mei
________________________________

**Comment by meihuisu** [comment]
Would

downloadQueueElem. removeChild(elemToRemove)

work on IE ?
If there are other problems under IE.. I don't mind to  skip IE.
________________________________

**Comment by levin422** [comment]
On which browser is 71c87d5 not working? Worked for me on Chrome and Firefox. 

The strategy generally would be to replace the native JavaScript function calls with jQuery ones since jQuery handles the JavaScript idiosyncrasies of IE and other browsers for us. But I don't think it's worth continuing work on that. 

Yes, as I said above I suggest we limit our supported browser list to:
- Firefox
- Chrome
- Safari
- Microsoft Edge

We can discuss with Scott Marshall when the time comes. Not a high priority at the moment.

**Comment by levin422** [comment]
During our 5/30/2019 call, Scott agreed to the browser requirements listed above. I've added them to the [user guide](https://github.com/SCECcode/CFM_web/blob/master/web/guide.php).
