### ISSUE TITLE
merge trace features with same name

### ISSUE THREAD

**Issue by andreasplesch** [SCECcode/CFM_web#4]
- is ingest with shp2pgsql overwriting: probably not

https://github.com/SCECcode/CFM_web/blob/master/schema/sql/linkup_traces.sql#L7

is maybe where only the first feature is linked although there may be multiple

A) keep two tables: one for traces, one for objects ? objects linked to traces by gid ?

B) or merge features of same name in preprocessing with ST_UNION or ST_COLLECT

**Comment by meihuisu** [comment]
This has been fixed in new version of CFM_web.  The schema for fault object now takes an array of traces.

**Comment by andreasplesch** [comment]
thanks
